const DOOMSDAY = new Date(2026, 11, 18, 0, 0, 0);

const ERAS = [
  {
    id: "foundation",
    name: "Foundation",
    tag: "MCU · Phase 1–3",
    color: "#e62429",
    blurb: "From a cave in Afghanistan to the snap. This is the spine of the universe.",
  },
  {
    id: "post-endgame",
    name: "Post-Endgame",
    tag: "The Multiverse Opens",
    color: "#9b59ff",
    blurb: "The world after the Blip. Phase 4–5 MCU before the multiverse fully detonates.",
  },
  {
    id: "spiderman",
    name: "Spider-Man Multiverse",
    tag: "Raimi + Webb",
    color: "#2d6cdf",
    blurb: "The other Peters. Then No Way Home hits different.",
  },
  {
    id: "venom",
    name: "Sony / Venom",
    tag: "Symbiote Universe",
    color: "#c9a227",
    blurb: "Eddie's side of the Sonyverse. Optional for Doomsday — solid for the bigger Spider picture.",
  },
  {
    id: "xmen",
    name: "X-Men",
    tag: "Fox Universe",
    color: "#3d8bff",
    blurb: "Mutants, time travel, and Deadpool crashing the party.",
  },
  {
    id: "fantastic-four",
    name: "Fantastic Four",
    tag: "A New Earth",
    color: "#f0c14b",
    blurb: "The First Family. First Steps.",
  },
  {
    id: "return",
    name: "Return to MCU",
    tag: "Phase 5–6",
    color: "#e62429",
    blurb: "Back on the main line. The board is set.",
  },
  {
    id: "destination",
    name: "Destination",
    tag: "December 18, 2026",
    color: "#e8c547",
    blurb: "It all leads here.",
  },
];

const CATALOG = [
  { id: "iron-man", watchKey: "iron-man", title: "Iron Man", year: 2008, type: "movie", era: "foundation", poster: "posters/iron-man.jpg" },
  { id: "iron-man-2", watchKey: "iron-man-2", title: "Iron Man 2", year: 2010, type: "movie", era: "foundation", poster: "posters/iron-man-2.jpg" },
  { id: "thor", watchKey: "thor", title: "Thor", year: 2011, type: "movie", era: "foundation", poster: "posters/thor.jpg" },
  { id: "ca-tfa", watchKey: "ca-tfa", title: "Captain America: The First Avenger", year: 2011, type: "movie", era: "foundation", poster: "posters/ca-tfa.jpg" },
  { id: "avengers", watchKey: "avengers", title: "The Avengers", year: 2012, type: "movie", era: "foundation", poster: "posters/avengers.jpg" },
  { id: "iron-man-3", watchKey: "iron-man-3", title: "Iron Man 3", year: 2013, type: "movie", era: "foundation", poster: "posters/iron-man-3.jpg" },
  { id: "ca-tws", watchKey: "ca-tws", title: "Captain America: The Winter Soldier", year: 2014, type: "movie", era: "foundation", poster: "posters/ca-tws.jpg" },
  { id: "gotg", watchKey: "gotg", title: "Guardians of the Galaxy", year: 2014, type: "movie", era: "foundation", poster: "posters/gotg.jpg" },
  { id: "aou", watchKey: "aou", title: "Avengers: Age of Ultron", year: 2015, type: "movie", era: "foundation", poster: "posters/aou.jpg" },
  { id: "ant-man", watchKey: "ant-man", title: "Ant-Man", year: 2015, type: "movie", era: "foundation", poster: "posters/ant-man.jpg" },
  { id: "civil-war", watchKey: "civil-war", title: "Captain America: Civil War", year: 2016, type: "movie", era: "foundation", poster: "posters/civil-war.jpg" },
  { id: "doctor-strange", watchKey: "doctor-strange", title: "Doctor Strange", year: 2016, type: "movie", era: "foundation", poster: "posters/doctor-strange.jpg" },
  { id: "gotg2", watchKey: "gotg2", title: "Guardians of the Galaxy Vol. 2", year: 2017, type: "movie", era: "foundation", poster: "posters/gotg2.jpg" },
  { id: "homecoming", watchKey: "homecoming", title: "Spider-Man: Homecoming", year: 2017, type: "movie", era: "foundation", poster: "posters/homecoming.jpg" },
  { id: "ragnarok", watchKey: "ragnarok", title: "Thor: Ragnarok", year: 2017, type: "movie", era: "foundation", poster: "posters/ragnarok.jpg" },
  { id: "black-panther", watchKey: "black-panther", title: "Black Panther", year: 2018, type: "movie", era: "foundation", poster: "posters/black-panther.jpg" },
  { id: "infinity-war", watchKey: "infinity-war", title: "Avengers: Infinity War", year: 2018, type: "movie", era: "foundation", poster: "posters/infinity-war.jpg" },
  { id: "amaw", watchKey: "amaw", title: "Ant-Man and the Wasp", year: 2018, type: "movie", era: "foundation", poster: "posters/amaw.jpg" },
  { id: "captain-marvel", watchKey: "captain-marvel", title: "Captain Marvel", year: 2019, type: "movie", era: "foundation", poster: "posters/captain-marvel.jpg" },
  { id: "endgame", watchKey: "endgame", title: "Avengers: Endgame", year: 2019, type: "movie", era: "foundation", poster: "posters/endgame.jpg" },

  { id: "ffh", watchKey: "ffh", title: "Spider-Man: Far From Home", year: 2019, type: "movie", era: "post-endgame", poster: "posters/ffh.jpg" },
  { id: "shang-chi", watchKey: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, type: "movie", era: "post-endgame", poster: "posters/shang-chi.jpg" },
  { id: "eternals", watchKey: "eternals", title: "Eternals", year: 2021, type: "movie", era: "post-endgame", poster: "posters/eternals.jpg" },
  { id: "black-widow", watchKey: "black-widow", title: "Black Widow", year: 2021, type: "movie", era: "post-endgame", poster: "posters/black-widow.jpg" },
  { id: "wandavision", watchKey: "wandavision", title: "WandaVision", year: 2021, type: "series", era: "post-endgame", poster: "posters/wandavision.jpg", rec: "Strongly recommended" },
  { id: "fatws", watchKey: "fatws", title: "The Falcon and the Winter Soldier — S1", year: 2021, type: "series", era: "post-endgame", poster: "posters/fatws.jpg", rec: "Essential for Brave New World / Thunderbolts*" },
  { id: "loki-s1", watchKey: "loki-s1", title: "Loki S1", year: 2021, type: "series", era: "post-endgame", poster: "posters/loki-s1.jpg", rec: "Extremely recommended" },
  { id: "loki-s2", watchKey: "loki-s2", title: "Loki S2", year: 2023, type: "series", era: "post-endgame", poster: "posters/loki-s2.jpg", rec: "Extremely recommended" },
  { id: "nwh", watchKey: "nwh", title: "Spider-Man: No Way Home", year: 2021, type: "movie", era: "post-endgame", poster: "posters/nwh.jpg" },
  { id: "mom", watchKey: "mom", title: "Doctor Strange in the Multiverse of Madness", year: 2022, type: "movie", era: "post-endgame", poster: "posters/mom.jpg" },
  { id: "love-and-thunder", watchKey: "love-and-thunder", title: "Thor: Love and Thunder", year: 2022, type: "movie", era: "post-endgame", poster: "posters/love-and-thunder.jpg" },
  { id: "wakanda-forever", watchKey: "wakanda-forever", title: "Black Panther: Wakanda Forever", year: 2022, type: "movie", era: "post-endgame", poster: "posters/wakanda-forever.jpg" },
  { id: "quantumania", watchKey: "quantumania", title: "Ant-Man and the Wasp: Quantumania", year: 2023, type: "movie", era: "post-endgame", poster: "posters/quantumania.jpg" },
  { id: "gotg3", watchKey: "gotg3", title: "Guardians of the Galaxy Vol. 3", year: 2023, type: "movie", era: "post-endgame", poster: "posters/gotg3.jpg" },
  { id: "ms-marvel", watchKey: "ms-marvel", title: "Ms. Marvel — S1", year: 2022, type: "series", era: "post-endgame", poster: "posters/ms-marvel.jpg", rec: "Essential before The Marvels" },
  { id: "the-marvels", watchKey: "the-marvels", title: "The Marvels", year: 2023, type: "movie", era: "post-endgame", poster: "posters/the-marvels.jpg" },

  { id: "spiderman-2002", watchKey: "spiderman-2002", title: "Spider-Man", year: 2002, type: "movie", era: "spiderman", poster: "posters/spiderman-2002.jpg" },
  { id: "spiderman-2", watchKey: "spiderman-2", title: "Spider-Man 2", year: 2004, type: "movie", era: "spiderman", poster: "posters/spiderman-2.jpg" },
  { id: "spiderman-3", watchKey: "spiderman-3", title: "Spider-Man 3", year: 2007, type: "movie", era: "spiderman", poster: "posters/spiderman-3.jpg" },
  { id: "tasm", watchKey: "tasm", title: "The Amazing Spider-Man", year: 2012, type: "movie", era: "spiderman", poster: "posters/tasm.jpg" },
  { id: "tasm2", watchKey: "tasm2", title: "The Amazing Spider-Man 2", year: 2014, type: "movie", era: "spiderman", poster: "posters/tasm2.jpg" },
  { id: "nwh-rewatch", watchKey: "nwh", title: "Spider-Man: No Way Home", year: 2021, type: "movie", era: "spiderman", poster: "posters/nwh.jpg", note: "Now you'll understand it properly.", rewatch: true },

  { id: "venom", watchKey: "venom", title: "Venom", year: 2018, type: "movie", era: "venom", poster: "posters/venom.jpg" },
  { id: "venom-2", watchKey: "venom-2", title: "Venom: Let There Be Carnage", year: 2021, type: "movie", era: "venom", poster: "posters/venom-2.jpg" },
  { id: "venom-3", watchKey: "venom-3", title: "Venom: The Last Dance", year: 2024, type: "movie", era: "venom", poster: "posters/venom-3.jpg" },

  { id: "xmen", watchKey: "xmen", title: "X-Men", year: 2000, type: "movie", era: "xmen", poster: "posters/xmen.jpg" },
  { id: "x2", watchKey: "x2", title: "X2", year: 2003, type: "movie", era: "xmen", poster: "posters/x2.jpg" },
  { id: "xmen-last-stand", watchKey: "xmen-last-stand", title: "X-Men: The Last Stand", year: 2006, type: "movie", era: "xmen", poster: "posters/xmen-last-stand.jpg" },
  { id: "xmen-first-class", watchKey: "xmen-first-class", title: "X-Men: First Class", year: 2011, type: "movie", era: "xmen", poster: "posters/xmen-first-class.jpg" },
  { id: "wolverine", watchKey: "wolverine", title: "The Wolverine", year: 2013, type: "movie", era: "xmen", poster: "posters/wolverine.jpg" },
  { id: "dofp", watchKey: "dofp", title: "X-Men: Days of Future Past", year: 2014, type: "movie", era: "xmen", poster: "posters/dofp.jpg" },
  { id: "apocalypse", watchKey: "apocalypse", title: "X-Men: Apocalypse", year: 2016, type: "movie", era: "xmen", poster: "posters/apocalypse.jpg" },
  { id: "dark-phoenix", watchKey: "dark-phoenix", title: "Dark Phoenix", year: 2019, type: "movie", era: "xmen", poster: "posters/dark-phoenix.jpg" },
  { id: "deadpool", watchKey: "deadpool", title: "Deadpool", year: 2016, type: "movie", era: "xmen", poster: "posters/deadpool.jpg" },
  { id: "deadpool-2", watchKey: "deadpool-2", title: "Deadpool 2", year: 2018, type: "movie", era: "xmen", poster: "posters/deadpool-2.jpg" },
  { id: "dpw", watchKey: "dpw", title: "Deadpool & Wolverine", year: 2024, type: "movie", era: "xmen", poster: "posters/dpw.jpg" },

  { id: "f4", watchKey: "f4", title: "The Fantastic Four: First Steps", year: 2025, type: "movie", era: "fantastic-four", poster: "posters/f4.jpg" },

  { id: "bnw", watchKey: "bnw", title: "Captain America: Brave New World", year: 2025, type: "movie", era: "return", poster: "posters/bnw.jpg" },
  { id: "thunderbolts", watchKey: "thunderbolts", title: "Thunderbolts*", year: 2025, type: "movie", era: "return", poster: "posters/thunderbolts.jpg" },
  { id: "brand-new-day", watchKey: "brand-new-day", title: "Spider-Man: Brand New Day", year: 2026, type: "movie", era: "return", poster: "posters/brand-new-day.jpg" },

  { id: "doomsday", watchKey: "doomsday", title: "Avengers: Doomsday", year: 2026, type: "movie", era: "destination", poster: "posters/doomsday.jpg", destination: true },
];
