const MASTER_TIERS = [
  {
    id: "tier-1",
    name: "Tier 1 · After Doomsday essentials",
    tag: "Highest value",
    color: "#e62429",
    blurb: "Defenders → Born Again → key Disney+ shows. Best Marvel per hour.",
  },
  {
    id: "tier-2",
    name: "Tier 2 · Multiverse & mutants",
    tag: "Payoff",
    color: "#9b59ff",
    blurb: "What If…?, Spider-Verse, X-Men '97, and the Fox leftovers you skipped.",
  },
  {
    id: "tier-3",
    name: "Tier 3 · MCU fill & specials",
    tag: "Phase glue",
    color: "#2d6cdf",
    blurb: "Secret Invasion, holiday specials, one-shots, Eyes of Wakanda, I Am Groot.",
  },
  {
    id: "tier-4",
    name: "Tier 4 · Sony completionist",
    tag: "Optional",
    color: "#c9a227",
    blurb: "Morbius, Madame Web, Kraven. Not required for continuity.",
  },
  {
    id: "tier-5",
    name: "Tier 5 · Marvel Television",
    tag: "ABC · Hulu",
    color: "#3d8bff",
    blurb: "Agent Carter, Agents of S.H.I.E.L.D., Runaways, Cloak & Dagger, Helstrom.",
  },
  {
    id: "tier-6",
    name: "Tier 6 · Theatrical archaeology",
    tag: "Legacy films",
    color: "#8b5a2b",
    blurb: "Blade, old FF, Daredevil, Ghost Rider, Punisher, and deep archive movies.",
  },
  {
    id: "tier-7",
    name: "Tier 7 · Animation archive",
    tag: "Deep dive",
    color: "#1aaa6e",
    blurb: "Classic Spider-Man & X-Men cartoons, animated movies, modern kids/series.",
  },
  {
    id: "tier-ref",
    name: "Reference · Docs & recaps",
    tag: "Not story",
    color: "#9b9588",
    blurb: "Legends, Assembled, 616 — use when you forgot a character. Not in story progress.",
  },
  {
    id: "tier-future",
    name: "Upcoming",
    tag: "Not out yet",
    color: "#e8c547",
    blurb: "Parked until release. Doomsday stays on the main Road track.",
  },
];

const MASTER_CATEGORIES = [
  { id: "mcu-series", name: "MCU Series", tag: "Live-action", color: "#e62429", blurb: "Disney+ MCU shows after your Doomsday path." },
  { id: "mcu-magic", name: "MCU Multiverse & Magic", tag: "Live-action", color: "#9b59ff", blurb: "Agatha, Ironheart, Secret Invasion." },
  { id: "specials", name: "Specials & One-Shots", tag: "Live-action shorts", color: "#f0c14b", blurb: "Werewolf by Night, Holiday Special, MCU One-Shots." },
  { id: "fox-extra", name: "Fox / X-Men leftovers", tag: "Live-action", color: "#3d8bff", blurb: "Origins, Logan, New Mutants, Legion, The Gifted." },
  { id: "sony-extra", name: "Sony Spider-Man Universe", tag: "Live-action", color: "#c9a227", blurb: "The Venom trilogy is already on Doomsday. This is the rest." },
  { id: "legacy-films", name: "Old Marvel movies", tag: "Live-action", color: "#8b5a2b", blurb: "Blade, Hulk 2003, old FF, Daredevil, Ghost Rider, archive." },
  { id: "defenders", name: "Netflix / Defenders", tag: "Live-action", color: "#a11d2e", blurb: "Watch order that leads into Born Again." },
  { id: "abc", name: "ABC / Marvel Television", tag: "Live-action", color: "#2d6cdf", blurb: "Agent Carter, Agents of S.H.I.E.L.D., Inhumans." },
  { id: "hulu", name: "Hulu / Marvel Television", tag: "Live-action", color: "#e87722", blurb: "Runaways, Cloak & Dagger, Helstrom." },
  { id: "anim-modern", name: "Modern animation", tag: "Animation", color: "#1aaa6e", blurb: "What If…?, Zombies, X-Men '97, Spider-Verse, I Am Groot, more." },
  { id: "anim-spidey", name: "Classic Spider-Man animation", tag: "Animation", color: "#2d6cdf", blurb: "1967 through Spectacular and Ultimate." },
  { id: "anim-xmen", name: "Classic X-Men animation", tag: "Animation", color: "#3d8bff", blurb: "TAS → Evolution → Wolverine and the X-Men → then '97." },
  { id: "anim-movies", name: "Old animated movies", tag: "Animation", color: "#6b8e23", blurb: "Ultimate Avengers, Planet Hulk, and the DTV era." },
  { id: "docs", name: "Documentary / recap", tag: "Reference", color: "#9b9588", blurb: "Not narrative. Recaps and making-of." },
  { id: "upcoming", name: "Upcoming", tag: "Future", color: "#e8c547", blurb: "Hold until release." },
];

/** Master Marvel backlog — NO Doomsday duplicates. LEGO skipped. */
const MASTER_CATALOG = [
  // Tier 1 — Defenders order then Born Again / priority MCU
  { id: "dd-s1", title: "Daredevil — S1", year: 2015, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Leads into Daredevil: Born Again", tmdb: "tv/61889", order: 10 },
  { id: "jj-s1", title: "Jessica Jones — S1", year: 2015, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Defenders saga", tmdb: "tv/61964", order: 20 },
  { id: "dd-s2", title: "Daredevil — S2", year: 2016, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Defenders saga", tmdb: "tv/61889", order: 30 },
  { id: "lc-s1", title: "Luke Cage — S1", year: 2016, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Defenders saga", tmdb: "tv/62126", order: 40 },
  { id: "if-s1", title: "Iron Fist — S1", year: 2017, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Defenders saga", tmdb: "tv/62127", order: 50 },
  { id: "defenders", title: "The Defenders", year: 2017, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Defenders saga", tmdb: "tv/62285", order: 60 },
  { id: "punisher-s1", title: "The Punisher — S1", year: 2017, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Pairs with The Punisher: One Last Kill", tmdb: "tv/67178", order: 70 },
  { id: "jj-s2", title: "Jessica Jones — S2", year: 2018, type: "series", track: "master", tier: "tier-1", category: "defenders", tmdb: "tv/61964", order: 80 },
  { id: "lc-s2", title: "Luke Cage — S2", year: 2018, type: "series", track: "master", tier: "tier-1", category: "defenders", tmdb: "tv/62126", order: 90 },
  { id: "if-s2", title: "Iron Fist — S2", year: 2018, type: "series", track: "master", tier: "tier-1", category: "defenders", tmdb: "tv/62127", order: 100 },
  { id: "dd-s3", title: "Daredevil — S3", year: 2018, type: "series", track: "master", tier: "tier-1", category: "defenders", matches: "Leads into Daredevil: Born Again", tmdb: "tv/61889", order: 110 },
  { id: "punisher-s2", title: "The Punisher — S2", year: 2019, type: "series", track: "master", tier: "tier-1", category: "defenders", tmdb: "tv/67178", order: 120 },
  { id: "jj-s3", title: "Jessica Jones — S3", year: 2019, type: "series", track: "master", tier: "tier-1", category: "defenders", tmdb: "tv/61964", order: 130 },

  { id: "born-again-s1", title: "Daredevil: Born Again — S1", year: 2025, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "After Netflix Daredevil", tmdb: "tv/203742", order: 140 },
  { id: "born-again-s2", title: "Daredevil: Born Again — S2", year: 2026, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "After Born Again S1", tmdb: "tv/203742", order: 150 },
  { id: "punisher-olk", title: "The Punisher: One Last Kill", year: 2026, type: "special", track: "master", tier: "tier-1", category: "mcu-series", matches: "After Netflix Punisher / Born Again", tmdb: "tv/203742", order: 160, note: "2026 Marvel special" },

  { id: "fatws", title: "The Falcon and the Winter Soldier — S1", year: 2021, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "Pairs with Captain America: Brave New World / Thunderbolts*", tmdb: "tv/88396", order: 170 },
  { id: "hawkeye", title: "Hawkeye — S1", year: 2021, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "Leads into Echo", tmdb: "tv/88329", order: 180 },
  { id: "echo", title: "Echo — S1", year: 2024, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "After Hawkeye / Daredevil", tmdb: "tv/122555", order: 190 },
  { id: "moon-knight", title: "Moon Knight — S1", year: 2022, type: "series", track: "master", tier: "tier-1", category: "mcu-series", tmdb: "tv/92782", order: 200 },
  { id: "ms-marvel", title: "Ms. Marvel — S1", year: 2022, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "Pairs with The Marvels", tmdb: "tv/92783", order: 210 },
  { id: "she-hulk", title: "She-Hulk: Attorney-at-Law — S1", year: 2022, type: "series", track: "master", tier: "tier-1", category: "mcu-series", matches: "Pairs with Hulk lore / Daredevil cameo", tmdb: "tv/92749", order: 220 },
  { id: "agatha", title: "Agatha All Along — S1", year: 2024, type: "series", track: "master", tier: "tier-1", category: "mcu-magic", matches: "Pairs with WandaVision", tmdb: "tv/138501", order: 230 },
  { id: "ironheart", title: "Ironheart — S1", year: 2025, type: "series", track: "master", tier: "tier-1", category: "mcu-magic", matches: "Pairs with Black Panther / Wakanda Forever", tmdb: "tv/114472", order: 240 },
  { id: "wonder-man", title: "Wonder Man — S1", year: 2026, type: "series", track: "master", tier: "tier-1", category: "mcu-series", tmdb: "tv/222654", order: 250 },

  // Tier 2
  { id: "what-if-s1", title: "What If...? — S1", year: 2021, type: "series", track: "master", tier: "tier-2", category: "anim-modern", matches: "Pairs with whole MCU spine", tmdb: "tv/91363", order: 300 },
  { id: "what-if-s2", title: "What If...? — S2", year: 2023, type: "series", track: "master", tier: "tier-2", category: "anim-modern", tmdb: "tv/91363", order: 310 },
  { id: "what-if-s3", title: "What If...? — S3", year: 2024, type: "series", track: "master", tier: "tier-2", category: "anim-modern", tmdb: "tv/91363", order: 320 },
  { id: "marvel-zombies", title: "Marvel Zombies — S1", year: 2025, type: "series", track: "master", tier: "tier-2", category: "anim-modern", matches: "After What If...?", tmdb: "tv/202611", order: 330 },
  { id: "spider-verse", title: "Spider-Man: Into the Spider-Verse", year: 2018, type: "movie", track: "master", tier: "tier-2", category: "anim-modern", matches: "Pairs with Tobey/Andrew/NWH multiverse", tmdb: "movie/324857", order: 340 },
  { id: "across-spider-verse", title: "Spider-Man: Across the Spider-Verse", year: 2023, type: "movie", track: "master", tier: "tier-2", category: "anim-modern", matches: "After Into the Spider-Verse", tmdb: "movie/569094", order: 350 },
  { id: "xmen-tas", title: "X-Men: The Animated Series (1992)", year: 1992, type: "series", track: "master", tier: "tier-2", category: "anim-xmen", matches: "Leads into X-Men '97", tmdb: "tv/4656", order: 360 },
  { id: "xmen-97-s1", title: "X-Men '97 — S1", year: 2024, type: "series", track: "master", tier: "tier-2", category: "anim-modern", matches: "After X-Men: The Animated Series", tmdb: "tv/209867", order: 370 },
  { id: "xmen-97-s2", title: "X-Men '97 — S2", year: 2026, type: "series", track: "master", tier: "tier-2", category: "anim-modern", matches: "After X-Men '97 S1", tmdb: "tv/209867", order: 380 },
  { id: "origins-wolverine", title: "X-Men Origins: Wolverine", year: 2009, type: "movie", track: "master", tier: "tier-2", category: "fox-extra", matches: "Pairs with The Wolverine / Logan", tmdb: "movie/2080", order: 390 },
  { id: "logan", title: "Logan", year: 2017, type: "movie", track: "master", tier: "tier-2", category: "fox-extra", matches: "End of Fox Wolverine line", tmdb: "movie/263115", order: 400 },
  { id: "new-mutants", title: "The New Mutants", year: 2020, type: "movie", track: "master", tier: "tier-2", category: "fox-extra", matches: "Fox X-Men leftover", tmdb: "movie/340102", order: 410 },
  { id: "legion-s1", title: "Legion — S1", year: 2017, type: "series", track: "master", tier: "tier-2", category: "fox-extra", tmdb: "tv/67166", order: 420 },
  { id: "legion-s2", title: "Legion — S2", year: 2018, type: "series", track: "master", tier: "tier-2", category: "fox-extra", tmdb: "tv/67166", order: 430 },
  { id: "legion-s3", title: "Legion — S3", year: 2019, type: "series", track: "master", tier: "tier-2", category: "fox-extra", tmdb: "tv/67166", order: 440 },
  { id: "gifted-s1", title: "The Gifted — S1", year: 2017, type: "series", track: "master", tier: "tier-2", category: "fox-extra", tmdb: "tv/71118", order: 450 },
  { id: "gifted-s2", title: "The Gifted — S2", year: 2018, type: "series", track: "master", tier: "tier-2", category: "fox-extra", tmdb: "tv/71118", order: 460 },

  // Tier 3
  { id: "secret-invasion", title: "Secret Invasion — S1", year: 2023, type: "series", track: "master", tier: "tier-3", category: "mcu-magic", matches: "Pairs with Cap / Fury era", tmdb: "tv/114472", order: 500 },
  { id: "werewolf", title: "Werewolf by Night", year: 2022, type: "special", track: "master", tier: "tier-3", category: "specials", tmdb: "movie/1033219", order: 510 },
  { id: "gotg-holiday", title: "The Guardians of the Galaxy Holiday Special", year: 2022, type: "special", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Guardians of the Galaxy", tmdb: "movie/1119882", order: 520 },
  { id: "eyes-wakanda", title: "Eyes of Wakanda — S1", year: 2025, type: "series", track: "master", tier: "tier-3", category: "anim-modern", matches: "Pairs with Black Panther / Wakanda Forever", tmdb: "tv/243346", order: 530 },
  { id: "iamgroot-s1", title: "I Am Groot — S1", year: 2022, type: "series", track: "master", tier: "tier-3", category: "anim-modern", matches: "Pairs with Guardians", tmdb: "tv/114468", order: 540 },
  { id: "iamgroot-s2", title: "I Am Groot — S2", year: 2023, type: "series", track: "master", tier: "tier-3", category: "anim-modern", matches: "Pairs with Guardians", tmdb: "tv/114468", order: 550 },
  { id: "consultant", title: "The Consultant", year: 2011, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Iron Man 2 / Incredible Hulk era", tmdb: "movie/76535", order: 560 },
  { id: "funny-thing", title: "A Funny Thing Happened on the Way to Thor's Hammer", year: 2011, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Thor", tmdb: "movie/76535", order: 570 },
  { id: "item-47", title: "Item 47", year: 2012, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with The Avengers / Agents of S.H.I.E.L.D.", tmdb: "movie/76535", order: 580 },
  { id: "agent-carter-os", title: "Agent Carter (One-Shot)", year: 2013, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Leads into Agent Carter series", tmdb: "movie/76535", order: 590 },
  { id: "all-hail-king", title: "All Hail the King", year: 2014, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Iron Man 3 / Shang-Chi", tmdb: "movie/76535", order: 600 },
  { id: "team-thor", title: "Team Thor", year: 2016, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Thor / Age of Ultron", tmdb: "movie/76535", order: 610 },
  { id: "team-thor-2", title: "Team Thor: Part 2", year: 2017, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Thor", tmdb: "movie/76535", order: 620 },
  { id: "team-darryl", title: "Team Darryl", year: 2018, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Thor: Ragnarok", tmdb: "movie/76535", order: 630 },
  { id: "peters-todo", title: "Peter's To-Do List", year: 2019, type: "short", track: "master", tier: "tier-3", category: "specials", matches: "Pairs with Far From Home", tmdb: "movie/76535", order: 640 },

  // Tier 4 Sony
  { id: "morbius", title: "Morbius", year: 2022, type: "movie", track: "master", tier: "tier-4", category: "sony-extra", matches: "Sonyverse — after Venom trilogy (on Doomsday list)", tmdb: "movie/526896", order: 700 },
  { id: "madame-web", title: "Madame Web", year: 2024, type: "movie", track: "master", tier: "tier-4", category: "sony-extra", matches: "Sonyverse completionist", tmdb: "movie/634492", order: 710 },
  { id: "kraven", title: "Kraven the Hunter", year: 2024, type: "movie", track: "master", tier: "tier-4", category: "sony-extra", matches: "Sonyverse completionist", tmdb: "movie/539972", order: 720 },

  // Tier 5 ABC/Hulu
  { id: "agent-carter-s1", title: "Agent Carter — S1", year: 2015, type: "series", track: "master", tier: "tier-5", category: "abc", matches: "After Agent Carter one-shot / Cap TFA", tmdb: "tv/61550", order: 800 },
  { id: "agent-carter-s2", title: "Agent Carter — S2", year: 2016, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/61550", order: 810 },
  { id: "aos-s1", title: "Agents of S.H.I.E.L.D. — S1", year: 2013, type: "series", track: "master", tier: "tier-5", category: "abc", matches: "Pairs with The Avengers / Winter Soldier era", tmdb: "tv/1403", order: 820 },
  { id: "aos-s2", title: "Agents of S.H.I.E.L.D. — S2", year: 2014, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/1403", order: 830 },
  { id: "aos-s3", title: "Agents of S.H.I.E.L.D. — S3", year: 2015, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/1403", order: 840 },
  { id: "aos-s4", title: "Agents of S.H.I.E.L.D. — S4", year: 2016, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/1403", order: 850 },
  { id: "aos-s5", title: "Agents of S.H.I.E.L.D. — S5", year: 2017, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/1403", order: 860 },
  { id: "aos-s6", title: "Agents of S.H.I.E.L.D. — S6", year: 2019, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/1403", order: 870 },
  { id: "aos-s7", title: "Agents of S.H.I.E.L.D. — S7", year: 2020, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/1403", order: 880 },
  { id: "inhumans", title: "Inhumans — S1", year: 2017, type: "series", track: "master", tier: "tier-5", category: "abc", tmdb: "tv/68716", order: 890 },
  { id: "runaways-s1", title: "Runaways — S1", year: 2017, type: "series", track: "master", tier: "tier-5", category: "hulu", tmdb: "tv/67137", order: 900 },
  { id: "runaways-s2", title: "Runaways — S2", year: 2018, type: "series", track: "master", tier: "tier-5", category: "hulu", tmdb: "tv/67137", order: 910 },
  { id: "runaways-s3", title: "Runaways — S3", year: 2019, type: "series", track: "master", tier: "tier-5", category: "hulu", tmdb: "tv/67137", order: 920 },
  { id: "cloak-s1", title: "Cloak & Dagger — S1", year: 2018, type: "series", track: "master", tier: "tier-5", category: "hulu", tmdb: "tv/66190", order: 930 },
  { id: "cloak-s2", title: "Cloak & Dagger — S2", year: 2019, type: "series", track: "master", tier: "tier-5", category: "hulu", tmdb: "tv/66190", order: 940 },
  { id: "helstrom", title: "Helstrom — S1", year: 2020, type: "series", track: "master", tier: "tier-5", category: "hulu", tmdb: "tv/94305", order: 950 },

  // Tier 6 legacy films
  { id: "hulk-2003", title: "Hulk (2003)", year: 2003, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "NOT The Incredible Hulk (2008)", tmdb: "movie/1927", order: 1000 },
  { id: "blade", title: "Blade", year: 1998, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Legacy — before MCU Blade", tmdb: "movie/36647", order: 1010 },
  { id: "blade-2", title: "Blade II", year: 2002, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/36586", order: 1020 },
  { id: "blade-trinity", title: "Blade: Trinity", year: 2004, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/36648", order: 1030 },
  { id: "ff-2005", title: "Fantastic Four (2005)", year: 2005, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Legacy — First Steps is on Doomsday list", tmdb: "movie/9738", order: 1040 },
  { id: "ff-rise", title: "Fantastic Four: Rise of the Silver Surfer", year: 2007, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Legacy FF", tmdb: "movie/1979", order: 1050 },
  { id: "ff-2015", title: "Fantastic Four (2015)", year: 2015, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Legacy remake", tmdb: "movie/166424", order: 1060 },
  { id: "daredevil-2003", title: "Daredevil (2003)", year: 2003, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Before Netflix Daredevil / Born Again", tmdb: "movie/9480", order: 1070 },
  { id: "elektra", title: "Elektra", year: 2005, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "After Daredevil (2003)", tmdb: "movie/8967", order: 1080 },
  { id: "ghost-rider", title: "Ghost Rider", year: 2007, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/1250", order: 1090 },
  { id: "ghost-rider-2", title: "Ghost Rider: Spirit of Vengeance", year: 2011, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/18823", order: 1100 },
  { id: "punisher-2004", title: "The Punisher (2004)", year: 2004, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Legacy — before Netflix Punisher", tmdb: "movie/7220", order: 1110 },
  { id: "punisher-warzones", title: "Punisher: War Zone", year: 2008, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/13052", order: 1120 },
  { id: "howard-duck", title: "Howard the Duck", year: 1986, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", matches: "Archive — cameo ties in GotG", tmdb: "movie/10674", order: 1130 },
  { id: "punisher-1989", title: "The Punisher (1989)", year: 1989, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/8867", order: 1140 },
  { id: "cap-1990", title: "Captain America (1990)", year: 1990, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/13995", order: 1150 },
  { id: "nick-fury-1998", title: "Nick Fury: Agent of S.H.I.E.L.D. (1998)", year: 1998, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/21529", order: 1160 },
  { id: "man-thing", title: "Man-Thing (2005)", year: 2005, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", tmdb: "movie/12549", order: 1170 },
  { id: "generation-x", title: "Generation X (1996)", year: 1996, type: "movie", track: "master", tier: "tier-6", category: "legacy-films", note: "TV movie", tmdb: "movie/22975", order: 1180 },

  // Tier 7 animation archive
  { id: "yfn-s1", title: "Your Friendly Neighborhood Spider-Man — S1", year: 2025, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/209092", order: 1200 },
  { id: "yfn-s2", title: "Your Friendly Neighborhood Spider-Man — S2", year: 2026, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/209092", order: 1210 },
  { id: "marvels-spiderman", title: "Marvel's Spider-Man", year: 2017, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/72750", order: 1220 },
  { id: "emh", title: "Avengers: Earth's Mightiest Heroes", year: 2010, type: "series", track: "master", tier: "tier-7", category: "anim-modern", matches: "Best classic Avengers cartoon", tmdb: "tv/31866", order: 1230 },
  { id: "marvels-avengers", title: "Marvel's Avengers", year: 2013, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/44266", order: 1240 },
  { id: "marvels-gotg", title: "Marvel's Guardians of the Galaxy", year: 2015, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/62266", order: 1250 },
  { id: "moon-girl", title: "Marvel's Moon Girl and Devil Dinosaur", year: 2023, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/114718", order: 1260 },
  { id: "spidey-friends", title: "Marvel's Spidey and His Amazing Friends", year: 2021, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/120989", order: 1270 },
  { id: "marvel-rising", title: "Marvel Rising", year: 2018, type: "special", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "movie/526020", order: 1280 },
  { id: "ironman-awesome", title: "Marvel's Iron Man and His Awesome Friends", year: 2025, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/273829", order: 1290 },
  { id: "modok", title: "M.O.D.O.K. — S1", year: 2021, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/103768", order: 1300 },
  { id: "hit-monkey-s1", title: "Hit-Monkey — S1", year: 2021, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/106712", order: 1310 },
  { id: "hit-monkey-s2", title: "Hit-Monkey — S2", year: 2024, type: "series", track: "master", tier: "tier-7", category: "anim-modern", tmdb: "tv/106712", order: 1320 },

  { id: "spiderman-1967", title: "Spider-Man (1967)", year: 1967, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/4627", order: 1400 },
  { id: "spiderman-1981", title: "Spider-Man (1981)", year: 1981, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/4628", order: 1410 },
  { id: "spiderman-friends", title: "Spider-Man and His Amazing Friends", year: 1981, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/4629", order: 1420 },
  { id: "spiderman-1994", title: "Spider-Man (1994)", year: 1994, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/2219", order: 1430 },
  { id: "spiderman-unlimited", title: "Spider-Man Unlimited", year: 1999, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/4630", order: 1440 },
  { id: "spiderman-mtvas", title: "Spider-Man: The New Animated Series", year: 2003, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/4631", order: 1450 },
  { id: "spectacular", title: "The Spectacular Spider-Man", year: 2008, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/1326", order: 1460 },
  { id: "ultimate-spiderman", title: "Ultimate Spider-Man", year: 2012, type: "series", track: "master", tier: "tier-7", category: "anim-spidey", tmdb: "tv/38538", order: 1470 },

  { id: "xmen-evolution", title: "X-Men: Evolution", year: 2000, type: "series", track: "master", tier: "tier-7", category: "anim-xmen", tmdb: "tv/4657", order: 1500 },
  { id: "wolverine-xmen", title: "Wolverine and the X-Men", year: 2008, type: "series", track: "master", tier: "tier-7", category: "anim-xmen", tmdb: "tv/4658", order: 1510 },

  { id: "ultimate-avengers", title: "Ultimate Avengers", year: 2006, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/14609", order: 1600 },
  { id: "ultimate-avengers-2", title: "Ultimate Avengers 2", year: 2006, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/14611", order: 1610 },
  { id: "invincible-ironman", title: "The Invincible Iron Man", year: 2007, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/14613", order: 1620 },
  { id: "ds-sorcerer", title: "Doctor Strange: The Sorcerer Supreme", year: 2007, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/14620", order: 1630 },
  { id: "hulk-vs", title: "Hulk Vs.", year: 2009, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/19798", order: 1640 },
  { id: "planet-hulk", title: "Planet Hulk", year: 2010, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/39254", order: 1650 },
  { id: "thor-tales", title: "Thor: Tales of Asgard", year: 2011, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/59175", order: 1660 },
  { id: "technovore", title: "Iron Man: Rise of Technovore", year: 2013, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/185449", order: 1670 },
  { id: "heroes-united", title: "Iron Man & Hulk: Heroes United", year: 2013, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/230896", order: 1680 },
  { id: "avengers-confidential", title: "Avengers Confidential: Black Widow & Punisher", year: 2014, type: "movie", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "movie/256424", order: 1690 },
  { id: "super-hero-adventures", title: "Marvel Super Hero Adventures", year: 2017, type: "series", track: "master", tier: "tier-7", category: "anim-movies", tmdb: "tv/75085", order: 1700 },

  // Reference — excluded from story progress
  { id: "legends", title: "Marvel Studios: Legends", year: 2021, type: "series", track: "master", tier: "tier-ref", category: "docs", status: "reference", note: "Character recaps — watch when you've forgotten someone", tmdb: "tv/114472", order: 1800 },
  { id: "assembled", title: "Marvel Studios: Assembled", year: 2021, type: "series", track: "master", tier: "tier-ref", category: "docs", status: "reference", note: "Behind-the-scenes documentaries", tmdb: "tv/120089", order: 1810 },
  { id: "expanding-universe", title: "Marvel Studios: Expanding the Universe", year: 2019, type: "special", track: "master", tier: "tier-ref", category: "docs", status: "reference", tmdb: "movie/617995", order: 1820 },
  { id: "marvels-616", title: "Marvel's 616", year: 2020, type: "series", track: "master", tier: "tier-ref", category: "docs", status: "reference", tmdb: "tv/103516", order: 1830 },
  { id: "behind-mask", title: "Marvel's Behind the Mask", year: 2021, type: "series", track: "master", tier: "tier-ref", category: "docs", status: "reference", tmdb: "tv/125443", order: 1840 },
  { id: "hero-project", title: "Marvel's Hero Project", year: 2019, type: "series", track: "master", tier: "tier-ref", category: "docs", status: "reference", tmdb: "tv/91624", order: 1850 },

  // Upcoming
  { id: "beyond-spider-verse", title: "Spider-Man: Beyond the Spider-Verse", year: 2027, type: "movie", track: "master", tier: "tier-future", category: "upcoming", status: "upcoming", matches: "After Across the Spider-Verse", tmdb: "movie/569094", order: 1900, note: "Upcoming — not out yet" },
  { id: "secret-wars", title: "Avengers: Secret Wars", year: 2027, type: "movie", track: "master", tier: "tier-future", category: "upcoming", status: "upcoming", matches: "After Avengers: Doomsday", tmdb: "movie/1003598", order: 1910, note: "Upcoming — after Doomsday" },
  { id: "blade-mcu", title: "Blade (MCU)", year: 2028, type: "movie", track: "master", tier: "tier-future", category: "upcoming", status: "upcoming", matches: "After Blade trilogy archive", tmdb: "movie/335984", order: 1920, note: "Upcoming MCU" },
  { id: "visionquest", title: "VisionQuest", year: 2026, type: "series", track: "master", tier: "tier-future", category: "upcoming", status: "upcoming", matches: "Pairs with WandaVision", tmdb: "tv/213032", order: 1930, note: "Upcoming — listed Oct 2026" },
];

function hydrateMasterCatalog() {
  return MASTER_CATALOG.map((item) => ({
    ...item,
    watchKey: item.id,
    poster: "posters/master/" + item.id + ".jpg",
    status: item.status || "available",
  }));
}
